#!/usr/bin/php
<?php
	# Copyright (C) 2016 Gwinilts <gwionps@gmail.com>

	# This program is free software: you can redistribute it and/or modify
	# it under the terms of the GNU General Public License as published by
	# the Free Software Foundation, either version 3 of the License, or
	# (at your option) any later version.

	# This program is distributed in the hope that it will be useful,
	# but WITHOUT ANY WARRANTY; without even the implied warranty of
	# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	# GNU General Public License for more details.

	# You should have received a copy of the GNU General Public License
	# along with this program.  If not, see <http://www.gnu.org/licenses/>.

	function mem_info_split($itm) {
		$itm = trim(preg_replace("!\s+!", "", $itm), "kB");
		return explode(":", $itm);
	}

	$type = trim(`echo \$BLOCK_INSTANCE`);

	$status = trim(`cat /proc/meminfo | grep "MemTotal\|MemFree\|SwapTotal\|SwapFree"`);
	$status = explode("\n", $status);
	$status = array_map("mem_info_split", $status);

	$info = array();

	foreach ($status as $itm) {
		$info{$itm{0}} = (int)$itm{1};
	}

	$info{"MemUsed"} = $info{"MemTotal"} - $info{"MemFree"};
	$info{"SwapUsed"} = $info{"SwapTotal"} - $info{"SwapFree"};
	$info{"LoadRatio"} = ($info{"MemUsed"} + $info{"SwapUsed"}) / $info{"MemTotal"};

	switch ($type) {
		case "swap":
			printf("%.2f/%.2f\n", $info{"SwapUsed"}/1024/1024, $info{"SwapTotal"}/1024/1024);
			printf("%.2f/%.2f\n", $info{"SwapUsed"}/1024/1024, $info{"SwapTotal"}/1024/1024);
			break;
		case "ratio":
			printf("%.2f\n", $info{"LoadRatio"});
			printf("%.2f\n", $info{"LoadRatio"});
			if ($info{"LoadRatio"} > 1.75) {
				echo "#FF0000\n";
			} else if ($info{"LoadRatio"} > 1) {
				echo "#FFAE00\n";
			} else if ($info{"LoadRatio"} > 0.75) {
				echo "#FFF600\n";
			} else if ($info{"LoadRatio"} > 0.5) {
				echo "#A8FF00\n";
			} else {
				echo "#00CC00\n";
			}
			break;
		default:
			printf("%.2f/%.2f\n", $info{"MemUsed"}/1024/1024, $info{"MemTotal"}/1024/1024);
			printf("%.2f/%.2f\n", $info{"MemUsed"}/1024/1024, $info{"MemTotal"}/1024/1024);
	}
?>
